export const LOGIN_USER = "LOGIN_USER"
export const LOGIN_USER_ERROR = "LOGIN_USER_ERROR"
export const REGISTER_USER = "REGISTER_USER"
export const REGISTER_USER_ERROR = "REGISTER_USER_ERROR"
export const LOADING_USER = "REGISTER_USER_ERROR"
export const CLEAR_USER_ERROR = "CLEAR_USER_ERROR"
export const CHECK_USERNAME_EXIST = "CHECK_USERNAME_EXIST"
export const CHECK_USERNAME_EXIST_ERROR = "CHECK_USERNAME_EXIST_ERROR"



