export const LOGIN_USER = "LOGIN_USER"
export const LOGIN_USER_ERROR = "LOGIN_USER_ERROR"
export const REGISTER_USER = "REGISTER_USER"
export const REGISTER_USER_ERROR = "REGISTER_USER_ERROR"
export const LOADING_USER = "REGISTER_USER_ERROR"
export const CLEAR_USER_ERROR = "CLEAR_USER_ERROR"
export const SET_USER = "SET_USER"
export const SET_LOGOUT = "SET_LOGOUT"
export const SET_LOGOUT_ERROR = "LOGOUT_USER_ERROR"
export const CHECK_USERNAME_EXIST = "CHECK_USERNAME_EXIST"
export const CHECK_USERNAME_EXIST_ERROR = "CHECK_USERNAME_EXIST_ERROR"



export const GET_PRODUCTS = "GET_PRODUCTS"
export const GET_PRODUCTS_ERROR = "GET_PRODUCTS_ERROR"
export const GET_CATEGORY = "GET_CATEGORY"
export const LOADING_PRODUCTS = "LOADING_PRODUCTS"
export const LOADING_CATEGORY = "LOADING_CATEGORY"
export const GET_CATEGORY_ERROR = "GET_CATEGORY_ERROR"
export const GET_PRODUCT = "GET_PRODUCT"
export const GET_PRODUCT_ERROR = "GET_PRODUCT_ERROR"
export const GET_PRODUCTSBYCATEGORY = "GET_PRODUCTBYCATEGORY"
export const GET_PRODUCTSBYCATEGORY_ERROR = "GET_PRODUCTBYCATEGORY_ERROR"
export const SET_ACTIVECATEGORY = "SET_ACTIVECATEGORY"
export const CLEAR_ACTIVECATEGORY = "CLEAR_ACTIVECATEGORY"
export const SET_PRODUCTINITIALSTATE = "SET_PRODUCTINITIALSTATE"
export const CLEAR_PRODUCT = "CLEAR_PRODUCT"


export const GET_REVIEWSBYPRODUCT = "GET_REVIEWSBYPRODUCT"
export const GET_REVIEWSBYPRODUCT_ERROR = "GET_REVIEWSBYPRODUCT_ERROR"
export const LOADING_REVIEWS = "LOADING_REVIEWS"


export const GET_BANNERS = "GET_BANNERS"
export const GET_BANNERS_ERROR = "GET_BANNERS_ERROR"
export const LOADING_BANNERS = "LOADING_BANNERS"


export const GET_CART = "GET_CART"
export const GET_CART_ERROR = "GET_CART_ERROR"
export const DELETE_FROMCART = "DELETE_FROMCART"
export const LOADING_CART = "LOADING_CART"
export const LOADING_CART_ACTIONS = "LOADING_CART_ACTIONS"
export const GET_CART_LENGTH = "GET_CART_LENGTH"
export const DELETE_ONEPRODUCT = "DELETE_ONEPRODUCT"
export const ADD_TOCART = "ADD_TOCART"


export const SET_ORDERDATA = "SET_ORDERDATA"
export const SET_SHIPPMETHOD = "SET_SHIPPMETHOD"




